- name: First play
  hosts: my_hosts             # must match in the inventory
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print managed node facts
      ansible.builtin.debug:
        # var: ansible_facts
        # var: ansible_facts["distribution"]
        msg: {
          "dns": "{{ ansible_facts['dns'] }}",
          "os_name": "{{ ansible_facts['distribution'] }}",
          "os_version": "{{ ansible_facts['distribution_version'] }}",
          "python_version": "{{ ansible_facts['python_version'] }}",
          "selinux": "{{ ansible_facts['selinux'] }}",
        }


- name: Second play
  hosts: my_hosts             # must match in the inventory
  vars:
    fruit: "blueberries"
    vegetable: "sweet potatoes"
    pause_in_seconds: 0
  tasks:                      # tasks are executed in order
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print fruit variable
      ansible.builtin.debug:
        var: fruit

    - name: Pause for {{ pause_in_seconds | int }} seconds
      ansible.builtin.pause:
        seconds: "{{ pause_in_seconds | int }}"

    - name: Print vegetable variable
      ansible.builtin.debug:
        msg: "favorite vegetable: {{ vegetable }}"


- name: Third play
  hosts: my_hosts             # must match in the inventory
  # gather_facts: false
  environment:
    ENV_VAR: developement
  tasks:
    - name: Print dev environment variable
      ansible.builtin.debug: 
        msg: "Environment: {{ ansible_env.ENV_VAR }}"

    - name: Print production environment variable
      ansible.builtin.debug: 
        msg: "Environment: {{ ansible_env.ENV_VAR }}"
      environment:
        ENV_VAR: production