- name: First play
  hosts: my_hosts             # must match in the inventory
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print builtin variables
      ansible.builtin.debug:
        msg: {
          "ansible_check_mode": "{{ ansible_check_mode }}",
          "ansible_diff_mode": "{{ ansible_diff_mode }}",
          "ansible_version": "{{ ansible_version }}",
          "inventory_dir": "{{ inventory_dir }}",
          "inventory_file": "{{ inventory_file }}",
          "inventory_hostname": "{{ inventory_hostname }}",
          "playbook_dir": "{{ playbook_dir }}"
        }

    - name: Print managed node facts
      ansible.builtin.debug:
        # var: ansible_facts
        # var: ansible_facts["distribution"]
        msg: {
          "dns": "{{ ansible_facts['dns'] }}",
          "os_name": "{{ ansible_facts['distribution'] }}",
          "os_version": "{{ ansible_facts['distribution_version'] }}",
          "python_version": "{{ ansible_facts['python_version'] }}",
          "selinux": "{{ ansible_facts['selinux'] }}",
        }


- name: Second play
  hosts: my_hosts             # must match in the inventory
  vars:
    fruit: "blueberries"
    vegetable: "sweet potatoes"
    pause_in_seconds: 0
  tasks:                      # tasks are executed in order
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print fruit variable
      ansible.builtin.debug:
        var: fruit
      tags: fruit_tag

    - name: Pause for {{ pause_in_seconds | int }} seconds
      ansible.builtin.pause:
        seconds: "{{ pause_in_seconds | int }}"

    - name: Print vegetable variable
      ansible.builtin.debug:
        msg: "favorite vegetable: {{ vegetable }}"
      tags: vegetable_tag


- name: Third play
  hosts: my_hosts             # must match in the inventory
  # gather_facts: false       # default is true
  environment:
    ENV_VAR: development
  tasks:
    - name: Print dev environment variable
      ansible.builtin.debug: 
        # msg: "Environment: {{ ansible_env.ENV_VAR }}"
        var: ansible_env

    - name: Print production environment variable
      ansible.builtin.command: "echo $ENV_VAR" # use flag -vv to see print
      environment:
        ENV_VAR: production


- name: Fourth play
  hosts: my_hosts             # must match in the inventory
  tasks:
    - name: Check whoami
      ansible.builtin.command: whoami
      register: whoami_command_output

    - name: Print whoami
      ansible.builtin.debug:
        var: whoami_command_output.stdout_lines

    - name: Print detailed time information
      ansible.builtin.debug:
        var: ansible_date_time

    - name: Print time ISO8601
      ansible.builtin.debug:
        var: ansible_date_time.iso8601   # prints like Y-M-D-H-M-S