- name: My first play
  hosts: my_hosts             # must match in the inventory
  tasks:
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"