- name: This dynamic task is in a separate file
  ansible.builtin.debug:
    msg: "First task from a separate file."

- name: Another dynamic task is in a separate file
  ansible.builtin.debug:
    msg: "Second task from a separate file."