- name: Get Facts
  hosts: target_hosts             # must match in the inventory
  tasks:
    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print builtin variables
      ansible.builtin.debug:
        msg: {
          "ansible_check_mode": "{{ ansible_check_mode }}",
          "ansible_diff_mode": "{{ ansible_diff_mode }}",
          "ansible_version": "{{ ansible_version['full'] }}",
          "inventory_dir": "{{ inventory_dir }}",
          "inventory_file": "{{ inventory_file }}",
          "inventory_hostname": "{{ inventory_hostname }}",
          "playbook_dir": "{{ playbook_dir }}"
        }

    - name: Print managed node facts
      ansible.builtin.debug:
        # var: ansible_facts
        # var: ansible_facts["distribution"]
        msg: {
          "dns": "{{ ansible_facts['dns'] }}",
          "os_name": "{{ ansible_facts['distribution'] }}",
          "os_version": "{{ ansible_facts['distribution_version'] }}",
          "python_version": "{{ ansible_facts['python_version'] }}",
          "selinux": "{{ ansible_facts['selinux'] }}",
        }


- name: Print Debug Messages and Variables
  hosts: target_hosts             # must match in the inventory
  vars:
    fruit: "blueberries"
    vegetable: "sweet potatoes"
    pause_in_seconds: 0
  tasks:                      # tasks are executed in order
    - name: Ping my hosts
      ansible.builtin.ping:

    - name: Print message
      ansible.builtin.debug:
        msg: "Testing first message"

    - name: Print fruit variable
      ansible.builtin.debug:
        var: fruit
      tags: fruit_tag

    - name: Pause for {{ pause_in_seconds | int }} seconds
      ansible.builtin.pause:
        seconds: "{{ pause_in_seconds | int }}"

    - name: Print vegetable variable
      ansible.builtin.debug:
        msg: "favorite vegetable: {{ vegetable }}"
      tags: ["vegetable_tag", "example_tag"]


- name: Environment Varialbes
  hosts: target_hosts             # must match in the inventory
  gather_facts: false             # default is true
  tags: ["play_level_tag"]
  environment:
    ENV_VAR: development
  tasks:
    - name: Print dev environment variable
      ansible.builtin.debug: 
        # msg: "Environment: {{ ansible_env.ENV_VAR }}"
        var: ansible_env

    - name: Print production environment variable
      ansible.builtin.command: "echo $ENV_VAR" # use flag -vv to see print
      environment:
        ENV_VAR: production


- name: Shell Command & Date and Time
  hosts: target_hosts             # must match in the inventory
  tasks:
    - name: Check whoami
      ansible.builtin.command: whoami
      register: whoami_command_output

    - name: Print whoami
      ansible.builtin.debug:
        var: whoami_command_output.stdout_lines

    - name: Print detailed time information
      ansible.builtin.debug:
        var: ansible_date_time

    - name: Print time ISO8601
      ansible.builtin.debug:
        var: ansible_date_time.iso8601   # prints like Y-M-D-H-M-S


- name: Execute Python Script & Run Handlers
  hosts: target_hosts
  gather_facts: false
  tasks:
    - name: Execute Python script & Run Handlers
      ansible.builtin.script: 
        executable: python3 
        cmd: example.py
      register: python_script_raw_output
      notify:         # list of handler names
        - Python script execution Return (Status) Code
        - Did Python script task make changes

    - name: Print raw output of Python script
      ansible.builtin.debug:
        var: python_script_raw_output
        verbosity: 2  # only takes effect with -vv flag

    - name: Convert output of Python script to JSON
      ansible.builtin.set_fact:
        favorite_produce: "{{ python_script_raw_output.stdout | from_json }}"

      # 'register' variable common fields: 
      # stdout and stderr — output from command or shell tasks
      # rc — return code
      # changed — whether the task made a change
      # failed

    - name: Print JSON
      ansible.builtin.debug:
        var: favorite_produce


  handlers:
    - name: Python script execution Return (Status) Code
      ansible.builtin.debug:
        var: python_script_raw_output.rc # 0 is succes code

    - name: Did Python script task make changes
      ansible.builtin.debug:
        msg: " Python script 'changed' status is true"
      when: python_script_raw_output.changed == true


- name: Loops
  hosts: target_hosts
  gather_facts: false
  vars:
    fruits: ["cara cara", "raspberry", "kiwi"]
    vegetables: ["sweet potato", "kale", "spinach"]
  tasks:
    - name: Loop with_together
      ansible.builtin.debug: 
        msg: "fruit: {{ item.0 }} | vegetable: {{ item.1 }}"
      with_together: ["{{ fruits }}", "{{ vegetables }}"]

    - name: Loop with_indexed_items
      ansible.builtin.debug: 
        msg: "index: {{ item.0 }} | value_at_index: {{ item.1 }}"
      with_indexed_items: ["{{ fruits }}"]

    - name: Print the entire array
      ansible.builtin.debug:
        var: my_array
      vars:
        my_array:
          - apple
          - banana
          - orange

    - name: Print each array element
      ansible.builtin.debug:
        msg: "{{ item }}"
      loop: "{{ my_array }}"
      vars:
        my_array:
          - blueberries
          - orange
          - mango

    - name: Get the list of files
      ansible.builtin.find:
        paths: /usr/bin
        patterns: "*grep*"
      register: found_files

    - name: Print each file path
      ansible.builtin.debug:
        msg: "{{ item.path }}"
      loop: "{{ found_files.files | default([]) }}"

    - name: Install multiple packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        # - zip
        # - curl