- name: Get Facts
  hosts: target_hosts             # must match in the inventory
  tasks:
    - name: Add a line if it doesn't exist
      ansible.builtin.lineinfile:
        path: sample.conf
        line: 'timeout 60'
        insertafter: '^port'
        state: present

    - name: Replace a line if it already exists
      ansible.builtin.lineinfile:
        path: sample.conf
        regexp: "ssl_enabled.*"  # .* matches everything after ssl_enabled
        line: "ssl_enabled true"

    - name: Add a line at the beginning of the file
      ansible.builtin.lineinfile:
        path: sample.conf
        line: "# sample network config file\n"
        insertbefore: BOF    # BOF: beginning of file

    - name: Read file content using 'cat' command
      ansible.builtin.command: cat sample.conf
      register: sample_conf_file_content

    - name: Print sample_conf_file_content
      ansible.builtin.debug:
        msg: "{{ sample_conf_file_content.stdout }}"

    - name: Remove a file if it already exists
      ansible.builtin.lineinfile:
        path: sample.conf
        regexp: ".*meaningless.*"
        state: absent